apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata: # kpt-merge: new-bp/new-bp-viewer
  name: new-bp-viewer
  namespace: test99
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: User
  name: morgantep@google.com
